# Messages for AuthPlugin
messages:
  only-players: "&cThis command can only be used by players!"
  reg-usage: "&cUsage: /reg [password]"
  reg-already-registered: "&cYou are already registered! Use /log [password] to login."
  reg-success: "&aSuccessfully registered! Now login with /log [password]"
  log-usage: "&cUsage: /log [password]"
  log-not-registered: "&cYou need to register first using /reg [password]"
  log-already-logged-in: "&cYou are already logged in!"
  log-success: "&aSuccessfully logged in! Welcome to the game!"
  log-wrong-password: "&cIncorrect password!"
  log-main-world-not-found: "&cMain world not found!"
  join-new-player: "&eWelcome! Please register using /reg [password]"
  join-returning-player: "&eWelcome back! Please login using /log [password]"
  move-not-registered: "&cPlease register first using /reg [password]"
  move-not-logged-in: "&cPlease login using /log [password]"

# Player data
players:
# Example entry (will be populated dynamically)
# ExamplePlayer:
#   password: "examplepassword"